name: Update IPTV Playlist
on:
  schedule:
    - cron: '0 0 * * *' # Chạy tự động vào 0h00 mỗi ngày (theo chuẩn UTC)
  workflow_dispatch: # Cho phép bạn bấm chạy thủ công để test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cài đặt thư viện
        run: pip install requests

      - name: Chạy Tool Quét Kênh
        run: python update_iptv.py

      - name: Lưu file m3u lên Github
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add daily_playlist.m3u
          git commit -m "Auto update playlist" || echo "No changes to commit"
          git pull --rebase origin main
          git push
